### ISSUE TITLE
Update to API v1.2 endpoints

### ISSUE THREAD

**Issue by agraebe** [stevenmaguire/uber-php#11]
Uber recently [announced](https://developer.uber.com/docs/riders/change-log) v1.2 endpoints for the Rides API. The following changes would be required to upgrade:
1. API base URL would need to reflect the version bump: ``https://api.uber.com/v1.2/``. [Sample endpoint](https://developer.uber.com/docs/riders/references/api/v1.2/me-get). 
2. A new ride request flow for upfront prices should be implemented, as [described here](https://developer.uber.com/docs/riders/ride-requests/tutorials/api/best-practices#upfront-fares)
3. All usage of rate limiting headers should be removed. [The headers are deprecated with v1.2](https://medium.com/uber-developers/announcing-riders-api-1-2-featuring-upfront-fares-ride-promotions-and-improved-dev-docs-7745135ca33f#.da7wwtnm8). A new endpoint to meet the needs will be created. Here are the impacted headers: `X-Rate-Limit-Limit`, `X-Rate-Limit-Remaining`, `X-Rate-Limit-Reset`.

**Comment by stevenmaguire** [comment]
With respect to the API version in the base url, you can control that via client configuration: 

``` php
$client = new Stevenmaguire\Uber\Client(array(
    'version'      => 'v1.2', 
    // other config
));
```

With that in mind, are you able to test the new functionality? What endpoints, if any, are missing here?

**Comment by agraebe** [comment]
@stevenmaguire I just updated the issue description. The v1.2 endpoints introduce a new ride request flow and we deprecated the rate limiting headers. 

@dustinwhittle can jump in to help I believe.

**Comment by stevenmaguire** [comment]
Ok. Thank you for clarifying some of these things. I have a couple follow-up questions, and I am assuming you can answer them as you appear to be part of the Uber team. 
1. How long will the current `v1` endpoints be supported? 
2. Will `v1` endpoints be supported along side `v1.2`?
3. Unless otherwise noted, will existing `v1` endpoints be accessible and function similarly in `v1.2`?
4. Will the `v1` endpoints still support the rate limit headers?
5. Is the "new ride request flow for upfront prices" brand new functionality or does it break existing pricing functionality?

**Comment by dustinwhittle** [comment]
1. We will support v1 until Q3 2017.
2. Yes, until they are fully deprecated we will support v1.
3. Yes, most of the v1.2 endpoints have the same v1 responses with the exception of (requests post/estimates). See the change log and api references for complete details. 
4. You should not rely on the existing rate limiting implementation as it will ultimately be deprecated. It is currently supported in v1.
5. The upfront fare flow was introduced when we added support for uber pool. We will start enforcing this in products/markets that support upfront fares in the v1.2 apis. The existing surge pricing and confirmation dialog/url will be supported until we deprecate the v1 apis.

Thanks for the awesome sdk and all of your effort so far. It would be great to work together to make the default flow using v1.2 apis and requesting an upfront fare by default. 

Please let us know if we can ever be of any help.

**Comment by stevenmaguire** [comment]
@agraebe @dustinwhittle I've spent some time refactoring the package a bit based on these latest changes. Instead of drawing a hard line in the same with respect to v1 and v1.2 I've updated the package to include the new endpoints and gracefully fail when older things do not work. What this means, is that the package still puts the developer in the drivers seat to decide which API version to use and how to handle exceptions along the way. Please feel free to review those changes in PR #12 and if you feel so inclined, build a local copy based on the branch and give it a run against your v1.2 test beds.

**Comment by stevenmaguire** [comment]
@agraebe @dustinwhittle I've just cut a new release of the client that includes these latest changes. Please let me know if anything unexpected comes up. In the mean time, I have a request of my own.

The Uber documentation lists this project as a community supported PHP library (thanks!) and indicates that its version requirement is "5+". This is not accurate and may cause grief for some folks. The current minimum requirement is 5.5+, even though 5.5. Are you in a position to update this?

https://developer.uber.com/docs/riders/guides/client-libraries

**Comment by dustinwhittle** [comment]
Sounds good. I will update the site to reflect 5.5+. Thanks for the awesome
work!
